<?php

use Illuminate\Database\Seeder;

class TimeZoneSeeder extends Seeder
{
    public function run()
    {
        $zones = 
        [
            ['display_name' => '(UTC-11:00) Midway Island, Samoa', 'code' => 'Pacific/Midway' ],
            ['display_name' => '(UTC-10:00) Hawaii-Aleutian', 'code' => 'America/Adak' ],
            ['display_name' => '(UTC-10:00) Hawaii', 'code' => 'Etc/GMT+10' ],
            ['display_name' => '(UTC-09:30) Marquesas Islands', 'code' => 'Pacific/Marquesas' ],
            ['display_name' => '(UTC-09:00) Gambier Islands', 'code' => 'Pacific/Gambier' ],
            ['display_name' => '(UTC-09:00) Alaska', 'code' => 'America/Anchorage' ],
            ['display_name' => '(UTC-08:00) Tijuana, Baja California', 'code' => 'America/Ensenada' ],
            ['display_name' => '(UTC-08:00) Pitcairn Islands', 'code' => 'Etc/GMT+8' ],
            ['display_name' => '(UTC-08:00) Pacific Time (US & Canada)', 'code' => 'America/Los_Angeles' ],
            ['display_name' => '(UTC-07:00) Mountain Time (US & Canada)', 'code' => 'America/Denver' ],
            ['display_name' => '(UTC-07:00) Chihuahua, La Paz, Mazatlan', 'code' => 'America/Chihuahua' ],
            ['display_name' => '(UTC-07:00) Arizona', 'code' => 'America/Dawson_Creek' ],
            ['display_name' => '(UTC-06:00) Saskatchewan, Central America', 'code' => 'America/Belize' ],
            ['display_name' => '(UTC-06:00) Guadalajara, Mexico City, Monterrey', 'code' => 'America/Cancun' ],
            ['display_name' => '(UTC-06:00) Easter Island', 'code' => 'Chile/EasterIsland' ],
            ['display_name' => '(UTC-06:00) Central Time (US & Canada)', 'code' => 'America/Chicago' ],
            ['display_name' => '(UTC-05:00) Eastern Time (US & Canada)', 'code' => 'America/New_York' ],
            ['display_name' => '(UTC-05:00) Cuba', 'code' => 'America/Havana' ],
            ['display_name' => '(UTC-05:00) Bogota, Lima, Quito, Rio Branco', 'code' => 'America/Bogota' ],
            ['display_name' => '(UTC-04:30) Caracas', 'code' => 'America/Caracas' ],
            ['display_name' => '(UTC-04:00) Santiago', 'code' => 'America/Santiago' ],
            ['display_name' => '(UTC-04:00) La Paz', 'code' => 'America/La_Paz' ],
            ['display_name' => '(UTC-04:00) Faukland Islands', 'code' => 'Atlantic/Stanley' ],
            ['display_name' => '(UTC-04:00) Brazil', 'code' => 'America/Campo_Grande' ],
            ['display_name' => '(UTC-04:00) Atlantic Time (Goose Bay)', 'code' => 'America/Goose_Bay' ],
            ['display_name' => '(UTC-04:00) Atlantic Time (Canada)', 'code' => 'America/Glace_Bay' ],
            ['display_name' => '(UTC-03:30) Newfoundland', 'code' => 'America/St_Johns' ],
            ['display_name' => '(UTC-03:00) UTC-3', 'code' => 'America/Araguaina' ],
            ['display_name' => '(UTC-03:00) Montevideo', 'code' => 'America/Montevideo' ],
            ['display_name' => '(UTC-03:00) Miquelon, St. Pierre', 'code' => 'America/Miquelon' ],
            ['display_name' => '(UTC-03:00) Greenland', 'code' => 'America/Godthab' ],
            ['display_name' => '(UTC-03:00) Buenos Aires', 'code' => 'America/Argentina/Buenos_Aires' ],
            ['display_name' => '(UTC-03:00) Brasilia', 'code' => 'America/Sao_Paulo' ],
            ['display_name' => '(UTC-02:00) Mid-Atlantic', 'code' => 'America/Noronha' ],
            ['display_name' => '(UTC-01:00) Cape Verde Is.', 'code' => 'Atlantic/Cape_Verde' ],
            ['display_name' => '(UTC-01:00) Azores', 'code' => 'Atlantic/Azores' ],
            ['display_name' => '(UTC) Greenwich Mean Time : Belfast', 'code' => 'Europe/Belfast' ],
            ['display_name' => '(UTC) Greenwich Mean Time : Dublin', 'code' => 'Europe/Dublin' ],
            ['display_name' => '(UTC) Greenwich Mean Time : Lisbon', 'code' => 'Europe/Lisbon' ],
            ['display_name' => '(UTC) Greenwich Mean Time : London', 'code' => 'Europe/London' ],
            ['display_name' => '(UTC) Monrovia, Reykjavik', 'code' => 'Africa/Abidjan' ],
            ['display_name' => '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', 'code' => 'Europe/Amsterdam' ],
            ['display_name' => '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', 'code' => 'Europe/Belgrade' ],
            ['display_name' => '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris', 'code' => 'Europe/Brussels' ],
            ['display_name' => '(UTC+01:00) West Central Africa', 'code' => 'Africa/Algiers' ],
            ['display_name' => '(UTC+01:00) Windhoek', 'code' => 'Africa/Windhoek' ],
            ['display_name' => '(UTC+02:00) Beirut', 'code' => 'Asia/Beirut' ],
            ['display_name' => '(UTC+02:00) Cairo', 'code' => 'Africa/Cairo' ],
            ['display_name' => '(UTC+02:00) Gaza', 'code' => 'Asia/Gaza' ],
            ['display_name' => '(UTC+02:00) Harare, Pretoria', 'code' => 'Africa/Blantyre' ],
            ['display_name' => '(UTC+02:00) Jerusalem', 'code' => 'Asia/Jerusalem' ],
            ['display_name' => '(UTC+02:00) Minsk', 'code' => 'Europe/Minsk' ],
            ['display_name' => '(UTC+02:00) Syria', 'code' => 'Asia/Damascus' ],
            ['display_name' => '(UTC+03:00) Moscow, St. Petersburg, Volgograd', 'code' => 'Europe/Moscow' ],
            ['display_name' => '(UTC+03:00) Nairobi', 'code' => 'Africa/Addis_Ababa' ],
            ['display_name' => '(UTC+03:30) Tehran', 'code' => 'Asia/Tehran' ],
            ['display_name' => '(UTC+04:00) Abu Dhabi, Muscat', 'code' => 'Asia/Dubai' ],
            ['display_name' => '(UTC+04:00) Yerevan', 'code' => 'Asia/Yerevan' ],
            ['display_name' => '(UTC+04:30) Kabul', 'code' => 'Asia/Kabul' ],
            ['display_name' => '(UTC+05:00) Ekaterinburg', 'code' => 'Asia/Yekaterinburg' ],
            ['display_name' => '(UTC+05:00) Tashkent', 'code' => 'Asia/Tashkent' ],
            ['display_name' => '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', 'code' => 'Asia/Kolkata' ],
            ['display_name' => '(UTC+05:45) Kathmandu', 'code' => 'Asia/Katmandu' ],
            ['display_name' => '(UTC+06:00) Astana, Dhaka', 'code' => 'Asia/Dhaka' ],
            ['display_name' => '(UTC+06:00) Novosibirsk', 'code' => 'Asia/Novosibirsk' ],
            ['display_name' => '(UTC+06:30) Yangon (Rangoon)', 'code' => 'Asia/Rangoon' ],
            ['display_name' => '(UTC+07:00) Bangkok, Hanoi, Jakarta', 'code' => 'Asia/Bangkok' ],
            ['display_name' => '(UTC+07:00) Krasnoyarsk', 'code' => 'Asia/Krasnoyarsk' ],
            ['display_name' => '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi', 'code' => 'Asia/Hong_Kong' ],
            ['display_name' => '(UTC+08:00) Irkutsk, Ulaan Bataar', 'code' => 'Asia/Irkutsk' ],
            ['display_name' => '(UTC+08:00) Perth', 'code' => 'Australia/Perth' ],
            ['display_name' => '(UTC+08:45) Eucla', 'code' => 'Australia/Eucla' ],
            ['display_name' => '(UTC+09:00) Osaka, Sapporo, Tokyo', 'code' => 'Asia/Tokyo' ],
            ['display_name' => '(UTC+09:00) Seoul', 'code' => 'Asia/Seoul' ],
            ['display_name' => '(UTC+09:00) Yakutsk', 'code' => 'Asia/Yakutsk' ],
            ['display_name' => '(UTC+09:30) Adelaide', 'code' => 'Australia/Adelaide' ],
            ['display_name' => '(UTC+09:30) Darwin', 'code' => 'Australia/Darwin' ],
            ['display_name' => '(UTC+10:00) Brisbane', 'code' => 'Australia/Brisbane' ],
            ['display_name' => '(UTC+10:00) Hobart', 'code' => 'Australia/Hobart' ],
            ['display_name' => '(UTC+10:00) Vladivostok', 'code' => 'Asia/Vladivostok' ],
            ['display_name' => '(UTC+10:30) Lord Howe Island', 'code' => 'Australia/Lord_Howe' ],
            ['display_name' => '(UTC+11:00) Solomon Is., New Caledonia', 'code' => 'Etc/GMT-11' ],
            ['display_name' => '(UTC+11:00) Magadan', 'code' => 'Asia/Magadan' ],
            ['display_name' => '(UTC+11:30) Norfolk Island', 'code' => 'Pacific/Norfolk' ],
            ['display_name' => '(UTC+12:00) Anadyr, Kamchatka', 'code' => 'Asia/Anadyr' ],
            ['display_name' => '(UTC+12:00) Auckland, Wellington', 'code' => 'Pacific/Auckland' ],
            ['display_name' => '(UTC+12:00) Fiji, Kamchatka, Marshall Is.', 'code' => 'Etc/GMT-12' ],
            ['display_name' => '(UTC+12:45) Chatham Islands', 'code' => 'Pacific/Chatham' ],
            ['display_name' => '(UTC+13:00) Nuku\'alofa', 'code' => 'Pacific/Tongatapu' ],
            ['display_name' => '(UTC+14:00) Kiritimati', 'code' => 'Pacific/Kiritimati' ],
        ];        

        \App\Models\TimeZone::insert($zones);

    }
}
